config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, except: [:new, :create]
  put 'users/:id/elevate' => 'users#elevate', as: :elevate_user

  resources :measures do
    collection do
      get :category
    end
    collection do
      get :tag
    end
  end

  resources :suggestions, only: [:new, :create]
  get '/terms' => 'static#terms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/measure.rb
class Measure < ApplicationRecord
  enum category: [:general, :individual, :relational, :community]
  has_one_attached :document
  validates_presence_of :title, :category, :description
  after_save :ensure_single_featured_measure
  acts_as_taggable

  def self.category_options
    Measure.categories.keys.map { |k| [k.to_s.capitalize, k] }.to_h
  end

  def to_s
    self.title
  end

  private

  def ensure_single_featured_measure
    if self.featured
      Measure.where('id != ?', self.id).update_all("featured = 'false'")
    end
  end

end

app/models/suggestion.rb
class Suggestion
  include ActiveModel::Model

  attr_accessor(
    :title,
    :category,
    :reference,
    :description
  )

  validates_presence_of :title, :reference, :description
  validates_presence_of :category, message: 'must be selected'

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:guest, :admin]

  validates_acceptance_of :terms_of_use
  validates_presence_of :role, :first_name, :last_name, :organization, :city, :state, :zip

  def to_s
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def require_admin
    unless current_user.admin?
      redirect_to root_path
      flash[:alert] = 'Restricted action, must be an administrator.'
    end
  end

  def after_sign_in_path_for(resource)
    measures_path
  end

end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController

  before_action :authenticate_user!
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_measure, only: [:show, :edit, :update, :destroy]

  def index
    @measures = Measure.order(:title)
    @featured_measure = @measures.detect { |measure| measure.featured == true }
  end

  def category
    if params[:category]
      @category = params[:category]
      @measures = Measure.where(category: @category.to_sym).order(:title)
    end
  end

  def tag
    if params[:tag]
      @category = params[:tag]
      @measures = Measure.tagged_with(@category).order(:title)
      render :category
    end
  end

  def show; end

  def new
    @measure = Measure.new
  end

  def edit; end

  def create
    @measure = Measure.new(measure_params)

    if @measure.save
      redirect_to @measure
      flash[:success] = 'Measure was successfully created.'
    else
      render :new
    end
  end

  def update
    if @measure.update(measure_params)
      redirect_to @measure
      flash[:success] = 'Measure was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @measure.destroy
    redirect_to measures_path
    flash[:success] = 'Measure was successfully destroyed.'
  end

  private

  def set_measure
    @measure = Measure.find(params[:id])
  end

  def measure_params
    params.require(:measure).permit(
      :title, :description, :details, :category, :tag_list, :document, :featured
    )
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  prepend_before_action :check_captcha, only: [:create]

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email,
      :organization, :city, :state, :zip, :phone, :password, :password_confirmation,
      :terms_of_use)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email,
      :organization, :city, :state, :zip, :phone, :password, :password_confirmation,
      :current_password, :terms_of_use)
  end

  def check_captcha
    unless verify_recaptcha
      self.resource = User.new sign_up_params
      resource.validate
      respond_with_navigational(resource) { render :new }
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home; end
  def terms; end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  before_action :authenticate_user!

  def new
    @suggestion = Suggestion.new
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)

    if @suggestion.valid? and verify_recaptcha
      SuggestionMailer.suggestion(current_user, suggestion_params).deliver
      redirect_to measures_url, notice: 'Thank you, your suggestion has been sent.'
    else
      flash[:recaptcha_error]
      render :new
    end
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:title, :category, :reference, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :require_admin, only: [:index, :destroy, :elevate]
  before_action :require_admin_or_current_user, only: [:show, :edit, :update]

  def index
    @admins = User.where(role: :admin)
    @guests = User.where(role: :guest)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:success] = "#{@user.to_s} successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to users_path(alert: 'Deleting your own account is prohibited.' )
    elsif @user.destroy
      redirect_to users_path
      flash[:success] = 'User successfully deleted.'
    end
  end

  def elevate
    @user = User.find(params[:id])
    @user.role = :admin
    if @user.save
      redirect_to users_path
      flash[:success] = "#{@user} is now an administrator."
    end
  end

  private

  def require_admin_or_current_user
    unless current_user.admin? or current_user == User.find(params[:id])
      redirect_to root_path
      flash[:alert] = 'Restricted action.'
    end
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :organization,
      :city, :state, :zip, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  BASE_TITLE = 'TRACES Resilience Measures'.freeze

  def full_title(page_title = '')
    page_title.empty? ? BASE_TITLE : "#{page_title} | #{BASE_TITLE}"
  end

  def form_errors_for(object)
    render partial: 'shared/form_errors', locals: { object: object }
  end

end

app/helpers/devise_helper.rb
# https://github.com/plataformatec/devise/wiki/Override-devise_error_messages!-for-views
module DeviseHelper

  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/measures_helper.rb
module MeasuresHelper

  def new_measure_link
    "#{link_to 'Add a new measure', new_measure_path, class: 'btn btn-primary float-right'}".html_safe
  end

end

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-sm
  = link_to image_tag('logo.png'), root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "nav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#nav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #nav.collapse.navbar-collapse.justify-content-end
    %ul.navbar-nav
      - if user_signed_in?
        %li.nav-link
          = link_to 'Home', measures_path
        %li.nav-link
          = link_to 'Shared', tag_measures_path(tag: 'shared')
        %li.nav-link
          = link_to 'General', category_measures_path(category: :general)
        %li.nav-link
          = link_to 'Individual', category_measures_path(category: :individual)
        %li.nav-link
          = link_to 'Relational', category_measures_path(category: :relational)
        %li.nav-link
          = link_to 'Community', category_measures_path(category: :community)
        %li.nav-item.dropdown
          %a#dropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
            = current_user
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdown"}
            - if current_user.admin?
              .dropdown-item
                = link_to 'Users', users_path
              .dropdown-item
                = link_to 'Add a Measure', users_path
            .dropdown-item
              = link_to 'My Profile', user_path(current_user)
            .dropdown-item
              = link_to 'Suggest a Measure', new_suggestion_path
            .dropdown-divider
            .dropdown-item
              = link_to 'Sign Out', destroy_user_session_path, method: :delete
      - else
        %li.nav-item.active
          .nav-link= link_to 'Sign In', new_user_session_path
          %span.sr-only (current)
        %li.nav-item.active
          .nav-link= link_to 'Register', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/nav'
    .container
      = render 'layouts/messages'
      = yield
    %footer
      %p
        © 2019 TRACEs Central Oregon. All rights reserved. Site by Nathan Struhs, Meah Cukrov, and Yong Bakos at OSU Cascades. Contact us at <a href="mailto:tracesmeasures@gmail.com">tracesmeasures@gmail.com</a>.
        = link_to image_tag('logo-osucascades.png'), 'https://osucascades.edu'

app/views/measures/_form.html.haml
= form_for(@measure, html: {multipart: true}) do |f|
  = form_errors_for(@measure)
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :details
    = f.text_area :details, rows: 5, class: 'form-control'
  .form-group
    = f.label :category
    = f.select 'category', options_for_select(Measure.category_options, @measure.persisted? ? @measure.category : 'Choose...'), {include_blank: 'Choose...'}, {class: 'form-control'}
  .form-group
    = f.label :tag_list, 'Tags (separated by commas)'
    = f.text_field :tag_list, class: 'form-control', value: @measure.tag_list.to_a.sort.to_sentence(last_word_connector: ', ')
  .form-group
    = f.label :document
    = f.file_field :document, accept: 'application/pdf', class: 'form-control-file'
  .form-group
    = f.check_box :featured
    = f.label :featured, 'Featured?'
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'

app/views/measures/category.html.haml
- provide(:title, "#{@category.capitalize} Resilience Measures")

= new_measure_link if current_user.admin?

%h1.display-4 #{@category.capitalize} Resilience Measures

%p= pluralize(@measures.size, 'Measure')

%ul.list-group
  - @measures.each do |measure|
    %li.list-group-item.my-2
      - if current_user.admin?
        .float-right
          = link_to 'Edit', edit_measure_path(measure), class: 'btn btn-sm btn-outline-secondary mx-4'
          = link_to 'Delete', measure, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
      %h3= link_to measure.title, measure
      %p.mb-0= measure.description
      .tag_list
        - measure.tag_list.sort.each do |tag|
          %span.tag= link_to tag, tag_measures_path(tag: tag)

app/views/measures/edit.html.haml
- provide(:title, 'Edit Resilience Measure')

%h1.display-4 Edit Resilience Measure
.float-right
  - if @measure.document.attached?
    %iframe{:src => "#{url_for(@measure.document)}", style: 'width: 400px; height: 550px;'}
  - else
    %h4 No document has been provided.
= render 'form'

app/views/measures/index.html.haml
- provide(:title, 'Resilience Measures')

.row.sub-banner
  .col.col-lg-3
    %h2 General
  .col.col-lg-3
    %h2 Individual
  .col.col-lg-3
    %h2 Relational
  .col.col-lg-3
    %h2 Community
.row
  .col.col-lg-3
    %p General measures are less specific, and depict an overall profile of resilience across psychological and physical criteria.
  .col.col-lg-3
    %p Individual measures focus on characterstics, such as a positive self-image, and developmental skills, such as problem-solving.
  .col.col-lg-3
    %p Relational factors include parenting competencies, caregiver well-being, positive peers, or living with family members.
  .col.col-lg-3
    %p Community-level factors focus on positive school environments, stable living situations, and economic opportunities.
.row
  .col
    %p= link_to 'Browse general measures »', category_measures_path(category: :general), class: 'btn btn-sm btn-primary'
  .col
    %p= link_to 'Browse individual measures »', category_measures_path(category: :individual), class: 'btn btn-sm btn-primary'
  .col
    %p= link_to 'Browse relational measures »', category_measures_path(category: :relational), class: 'btn btn-sm btn-primary'
  .col
    %p= link_to 'Browse community measures »', category_measures_path(category: :community), class: 'btn btn-sm btn-primary'

%p.text-center.my-5= link_to 'Have a suggestion for a new measure?', new_suggestion_path, class: 'btn btn-primary'

- if @featured_measure
  %h1.display-4.text-center Featured Measure
  %h2.text-center= @featured_measure.title
  %p.text-center= @featured_measure.description
  %p.text-center= @featured_measure.details.presence || "No details have been provided for this measure."
  - if @featured_measure.document.attached?
    %iframe.measure_document{:src => "#{url_for(@featured_measure.document)}"}
  - else
    %h4.text-center No document has been provided.
  %p.text-center= link_to 'View details', measure_path(@featured_measure), class: 'btn btn-primary'

app/views/measures/measures.html.haml
- provide(:title, "#{@category.capitalize} Resilience Measures")

= new_measure_link if current_user.admin?

%h1.display-4 #{@category.capitalize} Measures

%p= pluralize(@measures.size, 'Measure')

%ul.list-group
  - @measures.each do |measure|
    %li.list-group-item.my-2
      - if current_user.admin?
        .float-right
          = link_to 'Edit', edit_measure_path(measure), class: 'btn btn-sm btn-outline-secondary mx-4'
          = link_to 'Delete', measure, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
      %h3= link_to measure.title, measure

app/views/measures/new.html.haml
- provide(:title, 'New Resilience Measure')

%h1.display-4 New Resilience Measure

= render 'form'

app/views/measures/show.html.haml
- provide(:title, @measure.title)

- if current_user.admin?
  = link_to 'Edit', edit_measure_path(@measure), class: 'btn btn-primary float-right'

%h1.display-4.mb-5= @measure.title
.row
  .col
    - if @measure.document.attached?
      %iframe{:src => "#{url_for(@measure.document)}", style: 'width: 100%; height: 46em;'}
    - else
      %h4 No document has been provided.
  .col
    %h2= "A #{@measure.category} resilience measure"
    .tag_list
      - @measure.tag_list.to_a.sort.each do |tag|
        %span.tag= link_to tag, tag_measures_path(tag: tag)
    %p= @measure.description
    %p= @measure.details.presence || "No details have been provided for this measure."
    %p= "Added on #{@measure.created_at.to_s(:long)}."
    %p= "Last updated on #{@measure.created_at.to_s(:long)}."

app/views/shared/_form_errors.html.haml
- if object.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/suggestions/new.html.haml
- provide(:title, 'Suggest a Resilience Measure')

%h1.display-4 Suggest a Resilience Measure

= form_for @suggestion do |f|
  = form_errors_for(@suggestion)
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :category
    = f.select :category, options_for_select(Measure.category_options), {include_blank: 'Choose...'}, {class: 'form-control'}
  .form-group
    = f.label :reference
    = f.text_field :reference, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, rows: '10', class: 'form-control'
  .form-group
    = flash[:recaptcha_error]
    = recaptcha_tags
  .form-group
    = f.submit 'Submit', class: 'btn btn-primary form-control'

app/views/suggestions/suggestion.html.haml
%h1 Suggestion

= form_for :suggestion, url: 'suggestion' do |f|
  = f.label :title
  = f.text_field :title
  %br/
  = f.label :category
  = f.select :category, options_for_select(Measure.category_options)
  %br/
  = f.label :reference
  = f.text_field :reference
  %br/
  = f.label :description
  = f.text_area :description
  %br/
  = f.submit 'Submit', class: 'button'

app/views/users/_user.haml
%li.list-group-item.my-2{id: "user_#{user.id}"}
  = link_to user.to_s, edit_user_path(user)
  .float-right
    - unless user.admin?
      = link_to "Make admin", elevate_user_path(user), method: :put, data: { confirm: "Make #{user} an adminstrator?" }, class: 'btn btn-sm btn-outline-secondary mx-4'
    - if current_user != user
      = link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Delete #{user}?" }, class: 'btn btn-sm btn-outline-danger', title: "Delete #{user}"

app/views/users/edit.html.haml
- provide(:title, 'Edit Profile')

%h1.display-4 Edit Profile

= form_for(@user) do |f|
  = form_errors_for(@user)
  .form-group
    = f.label :email
    = f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control'
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :organization
    = f.text_field :organization, class: 'form-control'
  .form-group
    = f.label :city
    = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :state
    = f.text_field :state, class: 'form-control'
  .form-group
    = f.label :zip
    = f.text_field :zip, class: 'form-control'
  .form-group
    = f.label :phone
    = f.telephone_field :phone, class: 'form-control'
  .form-group
    = f.submit 'Update', class: 'btn btn-primary'

app/views/users/index.html.haml
- provide(:title, 'All Users')

%h1.display-4 All Users

%h2 Adminstrators
%ul#admins.list-group
  = render @admins

%h2 Guests
%ul#guests.list-group
  = render @guests

app/views/users/show.html.haml
- provide(:title, 'Profile')

.float-right= link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-primary'

%h1.display-4= @user.to_s

- if @user.admin?
  %p Administrator
%p= @user.organization
%p= @user.email
%p= "#{@user.city}, #{@user.state} #{@user.zip}"
%p= @user.phone